api:
  address: "localhost:8000"
mongo:
  host: localhost
  port: 27017
  db: crawlab_test
  username: ""
  password: ""
  authSource: "admin"
redis:
  address: localhost
  password: ""
  database: 1
  port: 6379
log:
  level: info
  path: "/var/logs/crawlab"
server:
  host: 0.0.0.0
  port: 8000
  master: "N"
  secret: "crawlab"
  register:
    # mac地址 或者 ip地址，如果是ip，则需要手动指定IP
    type: "mac"
    ip: ""
  settings:
     cache_life: 300  #UNIT: Second
     enable_register: true
     register_default_roles:
       - normal
spider:
  path: "/tmp/spiders"
task:
  workers: 4
other:
  tmppath: "/tmp"
